spring:
  datasource:
    url: jdbc:mysql://runningmen-db-test.cv7ugb7ql7hi.ap-northeast-2.rds.amazonaws.com/RUNNINGMEN
    username: runningmen
    password: umc_team23
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform=org:
      hibernate:
        spatial:
          dialect:
            mysql:
              MySQL56InnoDBSpatialDialect
        ddl-auto:
          create
      generate-ddl:
        false
    show-sql:
      true


jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK